### ISSUE TITLE
Installation Failure on W10 & Zotero 5.0.77

### ISSUE THREAD

**Issue by JayDugger** [leonkt/zotero-memento#1]
Following the instructions "download the repostiory, change the extension, install from file" returns this error from Zotero: 

> The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.

Zotero version 5.0.77

**Comment by stites** [comment]
Same error here on linux. I would really love to use this plugin!

**Comment by leonkt** [comment]
I have successfully downloaded the extension on a Windows 10 machine. However, could you try downloading the extension according to the new, updated instructions (zip the files in the folder, not the folder itself)?

**Comment by leonkt** [comment]
I have successfully downloaded the extension on a Windows 10 machine. Could you try downloading the extension according to the new, updated instructions (zip the files in the folder, not the folder itself)?

**Comment by erat-verbum** [comment]
That worked for me!! Strange that it doesn't work just using the downloaded .zip of the repository. Would it be worth having a 'releases' section on the GitHub page with a .xpi already ready?

Thank you!!

**Comment by leonkt** [comment]
Releases section is updated with the .XPI for convenience. Thanks!

**Comment by jmanthony3** [comment]
I am using Zotero 6.0.10 on Windows 10 and have run into a similar error with the plugin complaining about the compatibility with my version of Zotero.

![image](https://user-images.githubusercontent.com/62029937/183749435-a028ed28-7162-4c24-8746-64913b98f3a0.png)
