### ISSUE TITLE
manual "Archive this Resource" -> "Internet Archive" overwrites existing content in "extra" field

### ISSUE THREAD

**Issue by paregorios** [leonkt/zotero-memento#4]
# Environment:

- Zotero standalone 5.0.84
- macOS Mojave 10.14.6 (18G3020)
- Zotero addons installed:
   - Zotero Libreoffice Integration
   - Zotero Memento
   - Zotero Word for Mac Integration
   - Zutilo Utility for Zotero

# Steps to reproduce:

1. Install Zotero Memento using downloaded xpi from GitHub Release and restart Zotero standalone.
2. In Zotero standalone interface:
   a.  Navigate to a group library in which you have full permissions.
   b. Select an item that has valid content in the URL field, an "extra" field that contains text.
   c. Using the context menu on that item, select "Archive this Resource" -> "Internet Archive".
   __d. Observe that the "extra" field gets overwritten with an Internet Archive link, destroying the pre-existing content.

# Suggested alternative behavior:

If the "extra" field has non-whitespace content, append the Internet Archive link to the existing content after inserting a delimiter like ";". Alternatively,  omit writing the Internet Archive link to a non-empty extra field and just rely on the "note" attachment mechanism, but see issue #3.

**Comment by paregorios** [comment]
NB: overwrite of non-empty "extra" field occurs in both personal and group libraries.

**Comment by leonkt** [comment]
now retains the extra field; working on the group library issue.
