### ISSUE TITLE
Use http**s**://

### ISSUE THREAD

**Issue by salim-b** [leonkt/zotero-memento#6]
I really love this add-on, so first of all: Thank you very much for developing it!

Now, I noticed that archive links are always saved as

```url
http://web.archive.org/web/...
```

instead of

```url
https://web.archive.org/web/...
```

Since `web.archive.org` supports HTTPS, I guess there is really no need to use the insecure protocol. And because the site [doesn't automatically redirect](https://securityheaders.com/?q=web.archive.org&followRedirects=on) to its secure HTTPS counterpart when accessed over HTTP, users will always visit the insecure version if they don't use a browser add-on like [HTTPS Everywhere](https://www.eff.org/https-everywhere).

I briefly scanned the source (using [ack](https://beyondgrep.com/)) and detected the following places where `http://web.archive.org` is used instead of `https://web.archive.org`:

https://github.com/leonkt/zotero-memento/blob/bb4db7ee10095a46a0886935d4b4177b4e708488/chrome/content/scripts/IaPusher.js#L181

https://github.com/leonkt/zotero-memento/blob/7efbfb9591cea00ce7523441bc717aac22d4f6f7/chrome/content/Jasmine/jasmine-standalone-3.4.0/src/util_test.js#L118

Is there any specific reason that no HTTP**S** is used at these two places?

**Comment by leonkt** [comment]
Not particularly; good catch! I will make the appropriate changes.

**Comment by salim-b** [comment]
> I will make the appropriate changes.

Thanks, I've seen you have changed `IaPusher.js` accordingly in https://github.com/leonkt/zotero-memento/commit/e558a24e7745de9954fdf872b37374cb0fcd4160.

But shouldn't the jasmine test (see above) be updated as well?

Then I wanted to ask if you could release a new version including the recent changes :)
