### ISSUE TITLE
A few problems since update

### ISSUE THREAD

**Issue by element4l** [leonkt/zotero-memento#9]
First, whenever I choose Archive.is, I get an error window titled [Javascript Application] that spits out `"<h1>Invalid` `URL</h1>"` which comes back several times after closing it, followed by another error which barfs a huge html hairball in the error window. It also re-open several times after being closed. 

Second, when I use Internet Archive, Zotero hangs for over a full minute, presumably while it performs the archiving. In many instances, the archiving doesn't seem to work as no note is created.  edit: the Zotero hang also occurs whenever saving sources from the chrome companion.

Lastly, when it does work, the note it spits out is difficult to use because it's written in html. While notes seem to just display the html as code instead of rendering it. I don't know if there's a way to fix this. Comes out like this:

`Version URL: <a href="https://web.archive.org/web/20210327095606/https://www.feelguide.com/2015/06/14/neurotheology-team-proves-god-helmet-is-real-eliciting-mystic-states-visions-god-like-presence/" data-originalurl="https://www.feelguide.com/2015/06/14/neurotheology-team-proves-god-helmet-is-real-eliciting-mystic-states-visions-god-like-presence/" data-versiondate="2021-03-27T09:56:06Z">' Robust Link for: 'https://www.feelguide.com/2015/06/14/neurotheology-team-proves-god-helmet-is-real-eliciting-mystic-states-visions-god-like-presence/</a>`

That means that to visit the archived page, I have to manually go into the note, select only the web.archive text and differentiate it from the rest of the code, and paste that into the browser. In other words, the clickable link doesn't work here. Unless there is some plugin I'm missing that turns urls into clickable links in zotero notes. 

But until these issues are fixed (and I understand you're very busy with other things), I'm going to stick to saving webpages as PDFs and importing those into zotero.

**Comment by leonkt** [comment]
The functionality for Archive.is has not worked for a while now; I should have removed it (but forgot to!) Please stick to using IA. Also, try looking in the "Extra" field for a more readable link. I'll update the notification in the extension to reflect this. I'll see what I can do about the hanging...

**Comment by leonkt** [comment]
Hanging bug should be fixed in v1.1.1.

**Comment by element4l** [comment]
Thank you for the info about the extra field, and for fixing the hanging bug! Terrific.
